apiVersion: apps/v1
kind: Deployment
metadata:
  name: edukita-frontend
  namespace: edukita
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edukita-frontend
  template:
    metadata:
      labels:
        app: edukita-frontend
    spec:
      containers:
        - name: frontend
          image: edukita-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_BACKEND_URL
              value: "http://edukita-backend:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: edukita-frontend
  namespace: edukita
spec:
  selector:
    app: edukita-frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
